sass:
  style: compressed

collections:
  projects:
    output: true
  coursenotes:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "coursenotes"
    values:
      layout: "coursenote"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

highlighter: rouge


jekyll-minifier:
  compress_javascript: false # doesn't work, I am doing it manually

title: "Tristan Batchler's home page"
tagline: "A site for Tristan Batchler's details, and various computer science and maths blogs and articles"
description: "Find all the details you need to know about Tristan Batchler here. I am a detail oriented masters student skilled in systems and the technical support role with over seven years' professional experience in IT and software. I also write about tech and mathematics in my blog!"
url: "https://www.tbat.me"
author: "Tristan Batchler"
social:
    name: Tristan Batchler
    links:
      - https://www.linkedin.com/in/tristanbatchler
      - https://github.com/tristanbatchler
      - https://www.youtube.com/channel/UCk16fwaXxD4JUkxzwFc8PQg 
google_site_verification: "_4lemCjWeskGPkc0vFRR8MxPnEjnEjUzbFTK9HaeP7M"
locale: "en_AU"
